// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controls.proto

package org.eclipse.polarsys.rover.client.mqtt.proto;

public final class Controls {
  private Controls() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RoverControlsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PolarsysRover.RoverControls)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional sint32 left = 1;</code>
     */
    boolean hasLeft();
    /**
     * <code>optional sint32 left = 1;</code>
     */
    int getLeft();

    /**
     * <code>optional sint32 right = 2;</code>
     */
    boolean hasRight();
    /**
     * <code>optional sint32 right = 2;</code>
     */
    int getRight();
  }
  /**
   * Protobuf type {@code PolarsysRover.RoverControls}
   */
  public static final class RoverControls extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PolarsysRover.RoverControls)
      RoverControlsOrBuilder {
    // Use RoverControls.newBuilder() to construct.
    private RoverControls(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoverControls(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoverControls defaultInstance;
    public static RoverControls getDefaultInstance() {
      return defaultInstance;
    }

    public RoverControls getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoverControls(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              left_ = input.readSInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              right_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.polarsys.rover.client.mqtt.proto.Controls.internal_static_PolarsysRover_RoverControls_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.polarsys.rover.client.mqtt.proto.Controls.internal_static_PolarsysRover_RoverControls_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls.class, org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls.Builder.class);
    }

    public static com.google.protobuf.Parser<RoverControls> PARSER =
        new com.google.protobuf.AbstractParser<RoverControls>() {
      public RoverControls parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoverControls(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoverControls> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LEFT_FIELD_NUMBER = 1;
    private int left_;
    /**
     * <code>optional sint32 left = 1;</code>
     */
    public boolean hasLeft() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional sint32 left = 1;</code>
     */
    public int getLeft() {
      return left_;
    }

    public static final int RIGHT_FIELD_NUMBER = 2;
    private int right_;
    /**
     * <code>optional sint32 right = 2;</code>
     */
    public boolean hasRight() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional sint32 right = 2;</code>
     */
    public int getRight() {
      return right_;
    }

    private void initFields() {
      left_ = 0;
      right_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, left_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt32(2, right_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, left_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, right_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PolarsysRover.RoverControls}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PolarsysRover.RoverControls)
        org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControlsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Controls.internal_static_PolarsysRover_RoverControls_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Controls.internal_static_PolarsysRover_RoverControls_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls.class, org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls.Builder.class);
      }

      // Construct using org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        left_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        right_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Controls.internal_static_PolarsysRover_RoverControls_descriptor;
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls getDefaultInstanceForType() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls.getDefaultInstance();
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls build() {
        org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls buildPartial() {
        org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls result = new org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.left_ = left_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.right_ = right_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls) {
          return mergeFrom((org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls other) {
        if (other == org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls.getDefaultInstance()) return this;
        if (other.hasLeft()) {
          setLeft(other.getLeft());
        }
        if (other.hasRight()) {
          setRight(other.getRight());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.polarsys.rover.client.mqtt.proto.Controls.RoverControls) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int left_ ;
      /**
       * <code>optional sint32 left = 1;</code>
       */
      public boolean hasLeft() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional sint32 left = 1;</code>
       */
      public int getLeft() {
        return left_;
      }
      /**
       * <code>optional sint32 left = 1;</code>
       */
      public Builder setLeft(int value) {
        bitField0_ |= 0x00000001;
        left_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 left = 1;</code>
       */
      public Builder clearLeft() {
        bitField0_ = (bitField0_ & ~0x00000001);
        left_ = 0;
        onChanged();
        return this;
      }

      private int right_ ;
      /**
       * <code>optional sint32 right = 2;</code>
       */
      public boolean hasRight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional sint32 right = 2;</code>
       */
      public int getRight() {
        return right_;
      }
      /**
       * <code>optional sint32 right = 2;</code>
       */
      public Builder setRight(int value) {
        bitField0_ |= 0x00000002;
        right_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 right = 2;</code>
       */
      public Builder clearRight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        right_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PolarsysRover.RoverControls)
    }

    static {
      defaultInstance = new RoverControls(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PolarsysRover.RoverControls)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PolarsysRover_RoverControls_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PolarsysRover_RoverControls_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016controls.proto\022\rPolarsysRover\",\n\rRover" +
      "Controls\022\014\n\004left\030\001 \001(\021\022\r\n\005right\030\002 \001(\021B.\n" +
      ",org.eclipse.polarsys.rover.client.mqtt." +
      "proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PolarsysRover_RoverControls_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PolarsysRover_RoverControls_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PolarsysRover_RoverControls_descriptor,
        new java.lang.String[] { "Left", "Right", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
