// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensors.proto

package org.eclipse.polarsys.rover.client.mqtt.proto;

public final class Sensors {
  private Sensors() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AccelerationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PolarsysRover.Acceleration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 1;</code>
     */
    float getX();

    /**
     * <code>required float y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 2;</code>
     */
    float getY();

    /**
     * <code>required float z = 3;</code>
     */
    boolean hasZ();
    /**
     * <code>required float z = 3;</code>
     */
    float getZ();
  }
  /**
   * Protobuf type {@code PolarsysRover.Acceleration}
   */
  public static final class Acceleration extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PolarsysRover.Acceleration)
      AccelerationOrBuilder {
    // Use Acceleration.newBuilder() to construct.
    private Acceleration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Acceleration(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Acceleration defaultInstance;
    public static Acceleration getDefaultInstance() {
      return defaultInstance;
    }

    public Acceleration getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Acceleration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              x_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              y_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              z_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Acceleration_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Acceleration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.class, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.Builder.class);
    }

    public static com.google.protobuf.Parser<Acceleration> PARSER =
        new com.google.protobuf.AbstractParser<Acceleration>() {
      public Acceleration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Acceleration(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Acceleration> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>required float x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>required float y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>required float z = 3;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float z = 3;</code>
     */
    public float getZ() {
      return z_;
    }

    private void initFields() {
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, z_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PolarsysRover.Acceleration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PolarsysRover.Acceleration)
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.AccelerationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Acceleration_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Acceleration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.class, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.Builder.class);
      }

      // Construct using org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Acceleration_descriptor;
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration getDefaultInstanceForType() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.getDefaultInstance();
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration build() {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration buildPartial() {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration result = new org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration) {
          return mergeFrom((org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration other) {
        if (other == org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasZ()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float x_ ;
      /**
       * <code>required float x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>required float y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>required float z = 3;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float z = 3;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>required float z = 3;</code>
       */
      public Builder setZ(float value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float z = 3;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PolarsysRover.Acceleration)
    }

    static {
      defaultInstance = new Acceleration(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PolarsysRover.Acceleration)
  }

  public interface GyroOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PolarsysRover.Gyro)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 1;</code>
     */
    float getX();

    /**
     * <code>required float y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 2;</code>
     */
    float getY();

    /**
     * <code>required float z = 3;</code>
     */
    boolean hasZ();
    /**
     * <code>required float z = 3;</code>
     */
    float getZ();
  }
  /**
   * Protobuf type {@code PolarsysRover.Gyro}
   */
  public static final class Gyro extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PolarsysRover.Gyro)
      GyroOrBuilder {
    // Use Gyro.newBuilder() to construct.
    private Gyro(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Gyro(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Gyro defaultInstance;
    public static Gyro getDefaultInstance() {
      return defaultInstance;
    }

    public Gyro getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Gyro(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              x_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              y_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              z_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Gyro_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Gyro_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.class, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.Builder.class);
    }

    public static com.google.protobuf.Parser<Gyro> PARSER =
        new com.google.protobuf.AbstractParser<Gyro>() {
      public Gyro parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Gyro(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Gyro> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>required float x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>required float y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>required float z = 3;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float z = 3;</code>
     */
    public float getZ() {
      return z_;
    }

    private void initFields() {
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, z_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PolarsysRover.Gyro}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PolarsysRover.Gyro)
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.GyroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Gyro_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Gyro_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.class, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.Builder.class);
      }

      // Construct using org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Gyro_descriptor;
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro getDefaultInstanceForType() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.getDefaultInstance();
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro build() {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro buildPartial() {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro result = new org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro) {
          return mergeFrom((org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro other) {
        if (other == org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasZ()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float x_ ;
      /**
       * <code>required float x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>required float y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>required float z = 3;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float z = 3;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>required float z = 3;</code>
       */
      public Builder setZ(float value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float z = 3;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PolarsysRover.Gyro)
    }

    static {
      defaultInstance = new Gyro(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PolarsysRover.Gyro)
  }

  public interface CompassOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PolarsysRover.Compass)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 1;</code>
     */
    float getX();

    /**
     * <code>required float y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 2;</code>
     */
    float getY();

    /**
     * <code>required float z = 3;</code>
     */
    boolean hasZ();
    /**
     * <code>required float z = 3;</code>
     */
    float getZ();
  }
  /**
   * Protobuf type {@code PolarsysRover.Compass}
   */
  public static final class Compass extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PolarsysRover.Compass)
      CompassOrBuilder {
    // Use Compass.newBuilder() to construct.
    private Compass(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Compass(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Compass defaultInstance;
    public static Compass getDefaultInstance() {
      return defaultInstance;
    }

    public Compass getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Compass(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              x_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              y_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              z_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Compass_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Compass_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.class, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.Builder.class);
    }

    public static com.google.protobuf.Parser<Compass> PARSER =
        new com.google.protobuf.AbstractParser<Compass>() {
      public Compass parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Compass(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Compass> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>required float x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>required float y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>required float z = 3;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float z = 3;</code>
     */
    public float getZ() {
      return z_;
    }

    private void initFields() {
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, z_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PolarsysRover.Compass}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PolarsysRover.Compass)
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.CompassOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Compass_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Compass_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.class, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.Builder.class);
      }

      // Construct using org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_Compass_descriptor;
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass getDefaultInstanceForType() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.getDefaultInstance();
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass build() {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass buildPartial() {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass result = new org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass) {
          return mergeFrom((org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass other) {
        if (other == org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasZ()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float x_ ;
      /**
       * <code>required float x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>required float y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>required float z = 3;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float z = 3;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>required float z = 3;</code>
       */
      public Builder setZ(float value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float z = 3;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PolarsysRover.Compass)
    }

    static {
      defaultInstance = new Compass(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PolarsysRover.Compass)
  }

  public interface RoverSensorsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PolarsysRover.RoverSensors)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
     */
    boolean hasAccel();
    /**
     * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
     */
    org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration getAccel();
    /**
     * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
     */
    org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.AccelerationOrBuilder getAccelOrBuilder();

    /**
     * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
     */
    boolean hasGyro();
    /**
     * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
     */
    org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro getGyro();
    /**
     * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
     */
    org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.GyroOrBuilder getGyroOrBuilder();

    /**
     * <code>optional .PolarsysRover.Compass compass = 3;</code>
     */
    boolean hasCompass();
    /**
     * <code>optional .PolarsysRover.Compass compass = 3;</code>
     */
    org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass getCompass();
    /**
     * <code>optional .PolarsysRover.Compass compass = 3;</code>
     */
    org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.CompassOrBuilder getCompassOrBuilder();

    /**
     * <code>optional uint32 sonar = 4;</code>
     */
    boolean hasSonar();
    /**
     * <code>optional uint32 sonar = 4;</code>
     */
    int getSonar();
  }
  /**
   * Protobuf type {@code PolarsysRover.RoverSensors}
   */
  public static final class RoverSensors extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PolarsysRover.RoverSensors)
      RoverSensorsOrBuilder {
    // Use RoverSensors.newBuilder() to construct.
    private RoverSensors(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoverSensors(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoverSensors defaultInstance;
    public static RoverSensors getDefaultInstance() {
      return defaultInstance;
    }

    public RoverSensors getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoverSensors(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = accel_.toBuilder();
              }
              accel_ = input.readMessage(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(accel_);
                accel_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = gyro_.toBuilder();
              }
              gyro_ = input.readMessage(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(gyro_);
                gyro_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = compass_.toBuilder();
              }
              compass_ = input.readMessage(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(compass_);
                compass_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sonar_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_RoverSensors_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_RoverSensors_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors.class, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors.Builder.class);
    }

    public static com.google.protobuf.Parser<RoverSensors> PARSER =
        new com.google.protobuf.AbstractParser<RoverSensors>() {
      public RoverSensors parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoverSensors(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoverSensors> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ACCEL_FIELD_NUMBER = 1;
    private org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration accel_;
    /**
     * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
     */
    public boolean hasAccel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
     */
    public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration getAccel() {
      return accel_;
    }
    /**
     * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
     */
    public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.AccelerationOrBuilder getAccelOrBuilder() {
      return accel_;
    }

    public static final int GYRO_FIELD_NUMBER = 2;
    private org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro gyro_;
    /**
     * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
     */
    public boolean hasGyro() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
     */
    public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro getGyro() {
      return gyro_;
    }
    /**
     * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
     */
    public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.GyroOrBuilder getGyroOrBuilder() {
      return gyro_;
    }

    public static final int COMPASS_FIELD_NUMBER = 3;
    private org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass compass_;
    /**
     * <code>optional .PolarsysRover.Compass compass = 3;</code>
     */
    public boolean hasCompass() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .PolarsysRover.Compass compass = 3;</code>
     */
    public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass getCompass() {
      return compass_;
    }
    /**
     * <code>optional .PolarsysRover.Compass compass = 3;</code>
     */
    public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.CompassOrBuilder getCompassOrBuilder() {
      return compass_;
    }

    public static final int SONAR_FIELD_NUMBER = 4;
    private int sonar_;
    /**
     * <code>optional uint32 sonar = 4;</code>
     */
    public boolean hasSonar() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 sonar = 4;</code>
     */
    public int getSonar() {
      return sonar_;
    }

    private void initFields() {
      accel_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.getDefaultInstance();
      gyro_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.getDefaultInstance();
      compass_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.getDefaultInstance();
      sonar_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasAccel()) {
        if (!getAccel().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGyro()) {
        if (!getGyro().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasCompass()) {
        if (!getCompass().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, accel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, gyro_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, compass_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, sonar_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, accel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, gyro_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, compass_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, sonar_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PolarsysRover.RoverSensors}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PolarsysRover.RoverSensors)
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensorsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_RoverSensors_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_RoverSensors_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors.class, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors.Builder.class);
      }

      // Construct using org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAccelFieldBuilder();
          getGyroFieldBuilder();
          getCompassFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (accelBuilder_ == null) {
          accel_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.getDefaultInstance();
        } else {
          accelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (gyroBuilder_ == null) {
          gyro_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.getDefaultInstance();
        } else {
          gyroBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (compassBuilder_ == null) {
          compass_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.getDefaultInstance();
        } else {
          compassBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        sonar_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.internal_static_PolarsysRover_RoverSensors_descriptor;
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors getDefaultInstanceForType() {
        return org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors.getDefaultInstance();
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors build() {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors buildPartial() {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors result = new org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (accelBuilder_ == null) {
          result.accel_ = accel_;
        } else {
          result.accel_ = accelBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (gyroBuilder_ == null) {
          result.gyro_ = gyro_;
        } else {
          result.gyro_ = gyroBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (compassBuilder_ == null) {
          result.compass_ = compass_;
        } else {
          result.compass_ = compassBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sonar_ = sonar_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors) {
          return mergeFrom((org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors other) {
        if (other == org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors.getDefaultInstance()) return this;
        if (other.hasAccel()) {
          mergeAccel(other.getAccel());
        }
        if (other.hasGyro()) {
          mergeGyro(other.getGyro());
        }
        if (other.hasCompass()) {
          mergeCompass(other.getCompass());
        }
        if (other.hasSonar()) {
          setSonar(other.getSonar());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasAccel()) {
          if (!getAccel().isInitialized()) {
            
            return false;
          }
        }
        if (hasGyro()) {
          if (!getGyro().isInitialized()) {
            
            return false;
          }
        }
        if (hasCompass()) {
          if (!getCompass().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.RoverSensors) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration accel_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.Builder, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.AccelerationOrBuilder> accelBuilder_;
      /**
       * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
       */
      public boolean hasAccel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
       */
      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration getAccel() {
        if (accelBuilder_ == null) {
          return accel_;
        } else {
          return accelBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
       */
      public Builder setAccel(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration value) {
        if (accelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          accel_ = value;
          onChanged();
        } else {
          accelBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
       */
      public Builder setAccel(
          org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.Builder builderForValue) {
        if (accelBuilder_ == null) {
          accel_ = builderForValue.build();
          onChanged();
        } else {
          accelBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
       */
      public Builder mergeAccel(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration value) {
        if (accelBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              accel_ != org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.getDefaultInstance()) {
            accel_ =
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.newBuilder(accel_).mergeFrom(value).buildPartial();
          } else {
            accel_ = value;
          }
          onChanged();
        } else {
          accelBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
       */
      public Builder clearAccel() {
        if (accelBuilder_ == null) {
          accel_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.getDefaultInstance();
          onChanged();
        } else {
          accelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
       */
      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.Builder getAccelBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAccelFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
       */
      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.AccelerationOrBuilder getAccelOrBuilder() {
        if (accelBuilder_ != null) {
          return accelBuilder_.getMessageOrBuilder();
        } else {
          return accel_;
        }
      }
      /**
       * <code>optional .PolarsysRover.Acceleration accel = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.Builder, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.AccelerationOrBuilder> 
          getAccelFieldBuilder() {
        if (accelBuilder_ == null) {
          accelBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Acceleration.Builder, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.AccelerationOrBuilder>(
                  getAccel(),
                  getParentForChildren(),
                  isClean());
          accel_ = null;
        }
        return accelBuilder_;
      }

      private org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro gyro_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.Builder, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.GyroOrBuilder> gyroBuilder_;
      /**
       * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
       */
      public boolean hasGyro() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
       */
      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro getGyro() {
        if (gyroBuilder_ == null) {
          return gyro_;
        } else {
          return gyroBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
       */
      public Builder setGyro(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro value) {
        if (gyroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gyro_ = value;
          onChanged();
        } else {
          gyroBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
       */
      public Builder setGyro(
          org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.Builder builderForValue) {
        if (gyroBuilder_ == null) {
          gyro_ = builderForValue.build();
          onChanged();
        } else {
          gyroBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
       */
      public Builder mergeGyro(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro value) {
        if (gyroBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              gyro_ != org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.getDefaultInstance()) {
            gyro_ =
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.newBuilder(gyro_).mergeFrom(value).buildPartial();
          } else {
            gyro_ = value;
          }
          onChanged();
        } else {
          gyroBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
       */
      public Builder clearGyro() {
        if (gyroBuilder_ == null) {
          gyro_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.getDefaultInstance();
          onChanged();
        } else {
          gyroBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
       */
      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.Builder getGyroBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getGyroFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
       */
      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.GyroOrBuilder getGyroOrBuilder() {
        if (gyroBuilder_ != null) {
          return gyroBuilder_.getMessageOrBuilder();
        } else {
          return gyro_;
        }
      }
      /**
       * <code>optional .PolarsysRover.Gyro gyro = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.Builder, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.GyroOrBuilder> 
          getGyroFieldBuilder() {
        if (gyroBuilder_ == null) {
          gyroBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Gyro.Builder, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.GyroOrBuilder>(
                  getGyro(),
                  getParentForChildren(),
                  isClean());
          gyro_ = null;
        }
        return gyroBuilder_;
      }

      private org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass compass_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.Builder, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.CompassOrBuilder> compassBuilder_;
      /**
       * <code>optional .PolarsysRover.Compass compass = 3;</code>
       */
      public boolean hasCompass() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .PolarsysRover.Compass compass = 3;</code>
       */
      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass getCompass() {
        if (compassBuilder_ == null) {
          return compass_;
        } else {
          return compassBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PolarsysRover.Compass compass = 3;</code>
       */
      public Builder setCompass(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass value) {
        if (compassBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          compass_ = value;
          onChanged();
        } else {
          compassBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Compass compass = 3;</code>
       */
      public Builder setCompass(
          org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.Builder builderForValue) {
        if (compassBuilder_ == null) {
          compass_ = builderForValue.build();
          onChanged();
        } else {
          compassBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Compass compass = 3;</code>
       */
      public Builder mergeCompass(org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass value) {
        if (compassBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              compass_ != org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.getDefaultInstance()) {
            compass_ =
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.newBuilder(compass_).mergeFrom(value).buildPartial();
          } else {
            compass_ = value;
          }
          onChanged();
        } else {
          compassBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Compass compass = 3;</code>
       */
      public Builder clearCompass() {
        if (compassBuilder_ == null) {
          compass_ = org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.getDefaultInstance();
          onChanged();
        } else {
          compassBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .PolarsysRover.Compass compass = 3;</code>
       */
      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.Builder getCompassBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCompassFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PolarsysRover.Compass compass = 3;</code>
       */
      public org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.CompassOrBuilder getCompassOrBuilder() {
        if (compassBuilder_ != null) {
          return compassBuilder_.getMessageOrBuilder();
        } else {
          return compass_;
        }
      }
      /**
       * <code>optional .PolarsysRover.Compass compass = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.Builder, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.CompassOrBuilder> 
          getCompassFieldBuilder() {
        if (compassBuilder_ == null) {
          compassBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.Compass.Builder, org.eclipse.polarsys.rover.client.mqtt.proto.Sensors.CompassOrBuilder>(
                  getCompass(),
                  getParentForChildren(),
                  isClean());
          compass_ = null;
        }
        return compassBuilder_;
      }

      private int sonar_ ;
      /**
       * <code>optional uint32 sonar = 4;</code>
       */
      public boolean hasSonar() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 sonar = 4;</code>
       */
      public int getSonar() {
        return sonar_;
      }
      /**
       * <code>optional uint32 sonar = 4;</code>
       */
      public Builder setSonar(int value) {
        bitField0_ |= 0x00000008;
        sonar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 sonar = 4;</code>
       */
      public Builder clearSonar() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sonar_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PolarsysRover.RoverSensors)
    }

    static {
      defaultInstance = new RoverSensors(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PolarsysRover.RoverSensors)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PolarsysRover_Acceleration_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PolarsysRover_Acceleration_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PolarsysRover_Gyro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PolarsysRover_Gyro_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PolarsysRover_Compass_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PolarsysRover_Compass_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PolarsysRover_RoverSensors_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PolarsysRover_RoverSensors_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsensors.proto\022\rPolarsysRover\"/\n\014Accele" +
      "ration\022\t\n\001x\030\001 \002(\002\022\t\n\001y\030\002 \002(\002\022\t\n\001z\030\003 \002(\002\"" +
      "\'\n\004Gyro\022\t\n\001x\030\001 \002(\002\022\t\n\001y\030\002 \002(\002\022\t\n\001z\030\003 \002(\002" +
      "\"*\n\007Compass\022\t\n\001x\030\001 \002(\002\022\t\n\001y\030\002 \002(\002\022\t\n\001z\030\003" +
      " \002(\002\"\225\001\n\014RoverSensors\022*\n\005accel\030\001 \001(\0132\033.P" +
      "olarsysRover.Acceleration\022!\n\004gyro\030\002 \001(\0132" +
      "\023.PolarsysRover.Gyro\022\'\n\007compass\030\003 \001(\0132\026." +
      "PolarsysRover.Compass\022\r\n\005sonar\030\004 \001(\rB.\n," +
      "org.eclipse.polarsys.rover.client.mqtt.p" +
      "roto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PolarsysRover_Acceleration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PolarsysRover_Acceleration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PolarsysRover_Acceleration_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_PolarsysRover_Gyro_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PolarsysRover_Gyro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PolarsysRover_Gyro_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_PolarsysRover_Compass_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PolarsysRover_Compass_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PolarsysRover_Compass_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_PolarsysRover_RoverSensors_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PolarsysRover_RoverSensors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PolarsysRover_RoverSensors_descriptor,
        new java.lang.String[] { "Accel", "Gyro", "Compass", "Sonar", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
